development:
  adapter: sqlite3
  database: development.sqlite

test:
  adapter: sqlite3
  database: test.sqlite

production:
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  database: <%= ENV['DATABASE_NAME'] || 'sinatra' %>
  username: <%= ENV['DATABASE_USER'] || 'sinatra' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'sinatra' %>
  pool: 5
